#!/usr/bin/env bash

aProcessesNames=($(cat /etc/renice_processes_service/renice_processes_service.cfg | awk '{ print $1 }'))
aProcessesNices=($(cat /etc/renice_processes_service/renice_processes_service.cfg | awk '{ print int($2) }'))

for sProcessNameKey in "${!aProcessesNames[@]}"; do
	for sProcessID in `pgrep "${aProcessesNames[$sProcessNameKey]}"`; do
		# echo $sProcessID
		# cat /proc/$sProcessID/cmdline
		# echo ""
		# sNice=`cat /proc/$sProcessID/stat | awk '{ print $19}'`
		# if [ "$sNice" -eq "10" ]; then
			# echo "$sNice $sProcessID"
			# echo "renice -n ${aProcessesNices[$sProcessNameKey]} $sProcessID"
			renice -n ${aProcessesNices[$sProcessNameKey]} $sProcessID
		# fi
	done
done
